In [6]:
import pandas as pd
import numpy as np

In [74]:
df=pd.read_csv("HtWt.csv",encoding='windows-1252')

In [75]:
df.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [76]:
len(df["Height"])

50

In [77]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [78]:
df.describe()

Height      Weight
count  50.000000   50.000000
mean   69.096925  186.252335
std     2.730557   20.811387
min    63.456494  149.173566
25%    67.544146  169.497209
50%    68.930626  186.519547
75%    70.996769  197.670627
max    75.205974  241.893563

In [79]:
a=np.arange(1,51)

In [80]:
df.set_index(a)

Height      Weight
1   73.847017  241.893563
2   68.781904  162.310473
3   74.110105  212.740856
4   71.730978  220.042470
5   69.881796  206.349801
6   67.253016  152.212156
7   68.785081  183.927889
8   68.348516  167.971111
9   67.018950  175.929440
10  63.456494  156.399676
11  71.195382  186.604926
12  71.640805  213.741170
13  64.766329  167.127461
14  69.283070  189.446181
15  69.243732  186.434168
16  67.645620  172.186930
17  72.418317  196.028506
18  63.974326  172.883470
19  69.640060  185.983958
20  67.936005  182.426648
21  67.915050  174.115929
22  69.439440  197.731422
23  66.149132  149.173566
24  75.205974  228.761781
25  67.893196  162.006652
26  68.144033  192.343977
27  69.089631  184.435174
28  72.800844  206.828189
29  67.421242  175.213922
30  68.496415  154.342639
31  68.618111  187.506843
32  74.033808  212.910225
33  71.528216  195.032243
34  69.180161  205.183621
35  69.577202  204.164126
36  70.400929  192.903515
37  69.076171  197.488243
38  67.193523  183.810973
39  65.807316  163.851825
40  64.304188  163.108017
41  67.974336  172.135597
42  72.189426  194.045405
43  65.270346  168.617746
44  66.090177  161.193433
45  67.510322  164.660277
46  70.104786  188.922303
47  68.251836  187.060552
48  72.172709  209.070863
49  69.179858  192.014335
50  72.870360  211.342497

In [81]:
#visualization

In [82]:
from matplotlib import pyplot as plt

In [115]:
x=df['Height'].values.reshape((-1,1))
y=df['Weight']

In [116]:
x.ndim

2

In [117]:
x

array([[73.84701702],
       [68.78190405],
       [74.11010539],
       [71.7309784 ],
       [69.88179586],
       [67.25301569],
       [68.78508125],
       [68.34851551],
       [67.01894966],
       [63.45649398],
       [71.19538228],
       [71.64080512],
       [64.76632913],
       [69.2830701 ],
       [69.24373223],
       [67.6456197 ],
       [72.41831663],
       [63.97432572],
       [69.6400599 ],
       [67.93600485],
       [67.91505019],
       [69.43943987],
       [66.14913196],
       [75.20597361],
       [67.89319634],
       [68.1440328 ],
       [69.08963143],
       [72.80084352],
       [67.42124228],
       [68.49641536],
       [68.61811055],
       [74.03380762],
       [71.52821604],
       [69.1801611 ],
       [69.57720237],
       [70.40092889],
       [69.07617117],
       [67.19352328],
       [65.80731565],
       [64.30418789],
       [67.97433623],
       [72.18942596],
       [65.27034552],
       [66.09017738],
       [67.51032152],
       [70

In [118]:
x.shape

(50, 1)

In [119]:
x

array([[73.84701702],
       [68.78190405],
       [74.11010539],
       [71.7309784 ],
       [69.88179586],
       [67.25301569],
       [68.78508125],
       [68.34851551],
       [67.01894966],
       [63.45649398],
       [71.19538228],
       [71.64080512],
       [64.76632913],
       [69.2830701 ],
       [69.24373223],
       [67.6456197 ],
       [72.41831663],
       [63.97432572],
       [69.6400599 ],
       [67.93600485],
       [67.91505019],
       [69.43943987],
       [66.14913196],
       [75.20597361],
       [67.89319634],
       [68.1440328 ],
       [69.08963143],
       [72.80084352],
       [67.42124228],
       [68.49641536],
       [68.61811055],
       [74.03380762],
       [71.52821604],
       [69.1801611 ],
       [69.57720237],
       [70.40092889],
       [69.07617117],
       [67.19352328],
       [65.80731565],
       [64.30418789],
       [67.97433623],
       [72.18942596],
       [65.27034552],
       [66.09017738],
       [67.51032152],
       [70

In [120]:
plt.scatter(x,y)
plt.title("height and weight index")
plt.xlabel("Height")
plt.ylabel("Weight")

Text(0, 0.5, 'Weight')

In [121]:
from sklearn.linear_model import LinearRegression

In [122]:
linmodel=LinearRegression()

In [123]:
linmodel.fit(x,y)

LinearRegression()

In [130]:
print('intercept(b0):',linmodel.intercept_)

intercept(b0): -253.5383410652499


In [132]:
print("slope(b1):",linmodel.coef_)

slope(b1): [6.36483718]
