numpy

In [10]:
import numpy as np

In [11]:
#np.array([10,20,9]),b.ndim,b.shape,b.shape,b.itemsize,b.nbytes,b=np.zeros((2,3)),b=a.copy(),b=np.ones((2,3,5)),b=np.full((2,2),3),np.random.rand(2,3),np.asarray(a,dtype=int),np.identity(3),a=np.linspace(0,20,14,dtype=int),a=a.reshape(7,2),a.reshape(2,3),a.ravel(),b.flatten(),b.T,np.add(),np.sub(),np.multiply().np.divide(),np.dot(),np.sum(arr),arr1.sum(axis=1),np.min(axix=1,0),np.max,np.sqrt(arr),np.std(),np.log(),np.log10(),np.concatenate(a,b),np.hstach,vstack,np.split()

In [12]:
import numpy as np



a=np.array([10,20,9])                        #1D array
a.ndim

len(a)

b=np.array([[10,20],[34,44]])               #2D array
b
b.ndim
b




b.shape

b.shape

len(b)

b.itemsize

b.nbytes

b=np.array([[10,20,22,10,23,85,1],[34,44,63,51,203,112,17],[11,12,40,5,102,36,22]])

b[1][2]

b[1,:]

b[:,1]

dim3=np.array([[[10,20,1],[30,22,15]],[[5,10,20],[226,3,15]]])                #3D array

dim3.size

b=np.zeros((2,3))
b

#creating automatic array
b=np.ones((2,3,5))
b

b=np.full((2,2),3)
b

                            #indirectly creating
a=[23,55,2,32,13]
a=np.array(a,dtype=float,order='F')
a.dtype
a

a=np.random.rand(2,3)
a

a.dtype

a=np.asarray(a,dtype=int)

a

a=np.identity(3)                       #identity matix
a

                            #copy function
a=[12,55,2,33,6,45,41,2,2,20,65,6,2]
b=a.copy()

b[0]=100

a

b

a

a=np.array(a)

a
a.size

a+a

a.size



13

In [13]:
a=np.empty((2,3))
a

array([[0.15224306, 0.1050475 , 0.67656724],
       [0.82320471, 0.69279427, 0.76377482]])

In [14]:
a1=np.full((3,3),5,dtype=str)
a1


array([['5', '5', '5'],
       ['5', '5', '5'],
       ['5', '5', '5']], dtype='<U1')

In [15]:
a1.shape


(3, 3)

In [16]:

a1=[23,11,2,5,44,5,6,23,312,3]
a1=np.array(a1)
a1

array([ 23,  11,   2,   5,  44,   5,   6,  23, 312,   3])

# ARANGE()

In [17]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a=np.arange(1,100,5)
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

# linspace()

In [19]:
a=np.linspace(0,20,14,dtype=int)
a

array([ 0,  1,  3,  4,  6,  7,  9, 10, 12, 13, 15, 16, 18, 20])

In [20]:
a.size

14

# reshape()

In [21]:
a=a.reshape(7,2)
a

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16],
       [18, 20]])

In [22]:
a.shape

(7, 2)

In [23]:
a.ndim

2

In [24]:
a3=np.linspace(0,20,16,dtype=int)

In [25]:
a3.reshape(2,2,4)

array([[[ 0,  1,  2,  4],
        [ 5,  6,  8,  9]],

       [[10, 12, 13, 14],
        [16, 17, 18, 20]]])

In [26]:
a3.shape

(16,)

In [27]:
a3.ndim

1

In [28]:
a=np.arange(0,20,2).reshape(2,5)
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [29]:
b=a.copy()

# RAVEL()  AND FLATTEN()

In [30]:
a.ravel()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [32]:
b.flatten()
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [33]:
b.shape

(2, 5)

In [34]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# transpose

In [35]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [36]:
b.transpose()

array([[ 0, 10],
       [ 2, 12],
       [ 4, 14],
       [ 6, 16],
       [ 8, 18]])

In [37]:
b.T

array([[ 0, 10],
       [ 2, 12],
       [ 4, 14],
       [ 6, 16],
       [ 8, 18]])

# mathematic operations using numpy

In [38]:
arr1=np.linspace(1,50,12,dtype=int).reshape(3,4)
arr2=np.arange(1,48,4).reshape(3,4)
print(arr1)
arr2

[[ 1  5  9 14]
 [18 23 27 32]
 [36 41 45 50]]


array([[ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])

In [39]:
arr1+arr2

array([[ 2, 10, 18, 27],
       [35, 44, 52, 61],
       [69, 78, 86, 95]])

In [40]:
np.add(arr1,arr2)

array([[ 2, 10, 18, 27],
       [35, 44, 52, 61],
       [69, 78, 86, 95]])

In [41]:
arr2-arr1

array([[ 0,  0,  0, -1],
       [-1, -2, -2, -3],
       [-3, -4, -4, -5]])

In [42]:
np.subtract(arr2,arr1)

array([[ 0,  0,  0, -1],
       [-1, -2, -2, -3],
       [-3, -4, -4, -5]])

In [43]:
arr1 / arr2

array([[1.        , 1.        , 1.        , 1.07692308],
       [1.05882353, 1.0952381 , 1.08      , 1.10344828],
       [1.09090909, 1.10810811, 1.09756098, 1.11111111]])

In [44]:
np.divide(arr1,arr2)

array([[1.        , 1.        , 1.        , 1.07692308],
       [1.05882353, 1.0952381 , 1.08      , 1.10344828],
       [1.09090909, 1.10810811, 1.09756098, 1.11111111]])

In [45]:
arr1

array([[ 1,  5,  9, 14],
       [18, 23, 27, 32],
       [36, 41, 45, 50]])

In [46]:
arr2

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])

In [47]:
arr1*arr2

array([[   1,   25,   81,  182],
       [ 306,  483,  675,  928],
       [1188, 1517, 1845, 2250]])

In [48]:
np.multiply(arr1,arr2)

array([[   1,   25,   81,  182],
       [ 306,  483,  675,  928],
       [1188, 1517, 1845, 2250]])

In [49]:
arr1 @ arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

# matrix multiplication

In [ ]:
np.dot(arr1,arr2)

In [ ]:
arr1

In [ ]:
arr1.max()

In [ ]:
arr1.argmax()

In [ ]:
arr1.max(axis=0)

In [ ]:
arr1.max(axis=1)

In [ ]:
arr1.min()

In [ ]:
arr1.argmin()

# 

In [ ]:
arr1

In [ ]:
arr1.min(axis=0)

In [ ]:
arr1.min(axis=1)

# sum of the array elements

In [ ]:
np.sum(arr1)

In [ ]:
arr1

In [ ]:
arr1.sum(axis=0)

In [ ]:
arr1.sum(axis=1)

In [ ]:
np.mean(arr1)

In [ ]:
np.sqrt(arr1)

In [ ]:
np.std(arr1)

In [ ]:
np.exp(arr1)

In [ ]:
np.log(arr1)

In [ ]:
np.log10(arr1)

# ACCESSING ELEMENTS

In [ ]:
a=np.linspace(4,30,25,dtype=int).reshape(5,5)
a

In [ ]:
a[1][3].ndim

In [ ]:
a[4]  #to accesss a row

In [ ]:
a[:,0]  #to access a column 

In [ ]:
a[:,2].ndim

In [ ]:
a

# to fetch a single column in 2d matrix

In [ ]:
a[:,0:1]

In [ ]:
a[0,:]

In [ ]:
a[:,3:5]

In [ ]:
a[:,1:3]

In [ ]:
a[1]

In [ ]:
a[0:1,:]

In [ ]:
a

In [ ]:
a[1:4,3:6]

In [ ]:
a

In [ ]:
a[:]

In [ ]:
a[:,:]

In [ ]:
a.itemsize

In [ ]:
a.dtype

In [ ]:
32/4

In [52]:
arr1=np.linspace(0,55,16,dtype=int).reshape(4,4)
arr1

array([[ 0,  3,  7, 11],
       [14, 18, 22, 25],
       [29, 33, 36, 40],
       [44, 47, 51, 55]])

In [53]:
arr2=np.arange(17,33).reshape(4,4)
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

# concatenation

In [51]:
np.concatenate((arr1,arr2))

array([[ 1,  5,  9, 14],
       [18, 23, 27, 32],
       [36, 41, 45, 50],
       [ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])

In [54]:
np.concatenate((arr1,arr2),axis=1)

array([[ 0,  3,  7, 11, 17, 18, 19, 20],
       [14, 18, 22, 25, 21, 22, 23, 24],
       [29, 33, 36, 40, 25, 26, 27, 28],
       [44, 47, 51, 55, 29, 30, 31, 32]])

In [50]:
np.vstack((arr1,arr2))

array([[ 1,  5,  9, 14],
       [18, 23, 27, 32],
       [36, 41, 45, 50],
       [ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])

In [55]:
np.hstack((arr1,arr2))

array([[ 0,  3,  7, 11, 17, 18, 19, 20],
       [14, 18, 22, 25, 21, 22, 23, 24],
       [29, 33, 36, 40, 25, 26, 27, 28],
       [44, 47, 51, 55, 29, 30, 31, 32]])

# 

In [60]:
arr1


array([[ 0,  3,  7, 11],
       [14, 18, 22, 25],
       [29, 33, 36, 40],
       [44, 47, 51, 55]])

In [ ]:
l=np.split(arr1,2)

In [ ]:
type(l)

In [ ]:
l1=l[0]
l1

In [ ]:
type(l1)

In [59]:
l=np.split(arr1,2,axis=1)
l

[array([[ 0,  3],
        [14, 18],
        [29, 33],
        [44, 47]]),
 array([[ 7, 11],
        [22, 25],
        [36, 40],
        [51, 55]])]

In [56]:
list=np.array([10,2,33,6,54,94,2,236])
list

array([ 10,   2,  33,   6,  54,  94,   2, 236])

In [57]:
list.size

8

In [62]:
l1=np.split(list,[2,5,7])
l1

[array([10,  2]), array([33,  6, 54]), array([94,  2]), array([236])]

In [63]:
l1=np.split(list,[2,5])
l1

[array([10,  2]), array([33,  6, 54]), array([ 94,   2, 236])]